"""adds about_me and last_seen fields to user model

Revision ID: 018e0e58bb48
Revises: 184e4bf820d8
Create Date: 2021-08-15 18:43:29.847254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018e0e58bb48'
down_revision = '184e4bf820d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
